In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [23]:
a=np.array([[1,2,3],[4,5,6],[25,6,7]])

In [24]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [25,  6,  7]])

In [25]:
range(1000)

range(0, 1000)

In [26]:
a=np.arange(1000)

In [27]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a.ndim

1

In [34]:
a=np.array([[1,2],[3,4]])

In [35]:
a.ndim

2

In [36]:
a.shape

(2, 2)

In [38]:
a.size

4

In [40]:
a.itemsize

4

In [41]:
a.dtype

dtype('int32')

In [42]:
a=np.array([[1,2],[3,4],[5,6]],dtype='float64')

In [43]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [44]:
a.itemsize

8

In [45]:
a.shape

(3, 2)

In [46]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [48]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [49]:
a.ravel()

array([1., 2., 3., 4., 5., 6.])

In [51]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [56]:
a.max()

6.0

In [60]:
a.min()


1.0

In [59]:
a.sum()

21.0

In [61]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [62]:
np.std(a)

1.707825127659933

In [63]:
a=np.array([1,2,3])
b=np.array([4,5,7])

In [64]:
a * 3

array([3, 6, 9])

In [65]:
a+b

array([ 5,  7, 10])

In [66]:
a-b

array([-3, -3, -4])

In [67]:
a/b

array([0.25      , 0.4       , 0.42857143])

In [68]:
a%b

array([1, 2, 3], dtype=int32)

In [69]:
a//b

array([0, 0, 0], dtype=int32)

In [70]:
a**b

array([   1,   32, 2187], dtype=int32)

In [ ]:
a +5

In [13]:
import numpy as np
import time
import sys
list=range(1000)
array=np.arange(1000)
print(sys.getsizeof(5)*1000)
print(array.size*array.itemsize)
#array take 4 bit
#list take 28 bytes

28000
4000


In [21]:
import numpy as np
import time
import sys
s=1000000
a_l=range(s)
b_l=range(s)
start=time.time()

result=[a_l[i] +b_l[i] for i in range(s) ]
print('list time=',(time.time()-start)*1000)

arr1=np.arange(s)
arr2=np.arange(s)


start=time.time()
arr3=arr1+arr2
print('array time=',(time.time()-start)*1000)

list time= 325.23560523986816
array time= 2.992868423461914


# Vectorization demo

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print('Vectorization version:' + str(1000*(toc-tic))+'ms')

c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()

print(c)
print('For loop:' + str(1000*(toc-tic)) +'ms')

249878.9111879338
Vectorization version:0.0ms
249878.91118793047
For loop:1697.0078945159912ms


# Broadcasting Example

In [15]:
A=np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [18]:
cal=0
cal=A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [24]:
percentage=100*A/cal.reshape(1,4)
print(percentage)


[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Python Numpy Vectors

In [29]:
a=np.random.randn(5)
print(a)


[-1.63115989 -0.23715197 -1.01951208  0.04280273  0.99236396]


In [30]:
print(a.shape)


(5,)


In [31]:
print(a.T)

[-1.63115989 -0.23715197 -1.01951208  0.04280273  0.99236396]


In [32]:
print(np.dot(a,a.T))

4.742946809506077


In [39]:
a=np.random.randn(5,1)
print(a)

[[ 1.94037509]
 [-1.01160681]
 [-0.752232  ]
 [ 1.13477968]
 [ 0.18531136]]


In [40]:
print(a.T)

[[ 1.94037509 -1.01160681 -0.752232    1.13477968  0.18531136]]


In [41]:
print(np.dot(a,a.T))

[[ 3.76505548 -1.96289666 -1.45961224  2.20189823  0.35957354]
 [-1.96289666  1.02334834  0.76096302 -1.14795086 -0.18746223]
 [-1.45961224  0.76096302  0.56585298 -0.85361759 -0.13939713]
 [ 2.20189823 -1.14795086 -0.85361759  1.28772493  0.21028756]
 [ 0.35957354 -0.18746223 -0.13939713  0.21028756  0.0343403 ]]
